name: build opencv osx
on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'OpenCV version(branch, tag or SHA)'
        required: true
        default: ''
jobs:
  build:
    strategy:
      matrix:
        include:
          - name: "macOS"
            os: macos-latest
            release_path: "build"
            platform: "osx"
            type: "desktop"

    runs-on: ${{ matrix.os }}
    name: ${{ matrix.name }}
    steps: 
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Checkout opencv
        uses: actions/checkout@v4
        with:
          repository: opencv/opencv
          ref: ${{ inputs.ref }}
          path: opencv

      - name: Modify opencv script
        if: ${{ matrix.type == 'desktop' }}
        run: python3 modify_opencv.py opencv
      
      - name: Configure Default
        if: ${{ (matrix.type != 'mobile') }}
        run: cmake -S ./opencv -DBUILD_SHARED_LIBS=OFF -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_PREFIX=./install -B ./build -C opencv_options.txt
      
      - name: Build Mobile
        if: ${{ matrix.type == 'mobile' }}
        run: ./build_${{ matrix.platform}}.sh

      - name: list dir
        run: ls

      - name: list dir 2
        run: ls opencv
      
      # - name: Build Desktop
      #   if: ${{ matrix.type == 'desktop' }}
      #   run: cmake --build ./build --config Release
      
      - name: Install Desktop
        if: ${{ matrix.type == 'desktop' }}
        run: cmake --build ./build --target install --config Release

      - name: move/rename install desktop
        run: |
          mkdir export
          mv install export/opencv
        if: ${{ matrix.type == 'desktop' }}
      
      - name: move/rename ios framework
        if: ${{ matrix.platform == 'ios' }}
        run: |
          mkdir export
          mv ios/opencv2.framework export/opencv2.framework
      
      - name: move/rename android sdk
        if: ${{ matrix.platform == 'android' }}
        run: |
          mkdir export
          mv android_sdk/OpenCV-android-sdk export/opencv

      - name: zip file non ios
        if: ${{ matrix.platform != 'ios' }}
        run: 7z a -r opencv-${{ inputs.ref }}-${{ matrix.platform }}.zip ./export/opencv

      - name: zip file ios
        if: ${{ matrix.platform == 'ios' }}
        run: 7z a -r opencv-${{ inputs.ref }}-${{ matrix.platform }}.zip ./export/opencv2.framework

      - name: list dependencies 1
        run: ls

      - name: list dependencies 2
        run: ls export
      
      # - name: unzip file
      #   run: |
      #     7z x dep.zip -odep_out
      
      - uses: actions/upload-artifact@v4
        name: upload artifacts
        with:
          name: artifact-${{ matrix.platform }}
          path: opencv-${{ inputs.ref }}-${{ matrix.platform }}.zip

  