name: build opencv android sdk

on:
  workflow_dispatch:
    inputs:
      ref:
        type: choice
        description: select opencv version
        options:
          - 4.5.5

jobs:
  build:


    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repo
        uses: actions/checkout@v3
      
      - name: Checkout opencv
        uses: actions/checkout@v3
        with:
          repository: opencv/opencv
          ref: ${{ inputs.ref }}
          path: opencv
        
      - name: display ndk
        run: echo $ANDRIOD_NDK_TOOLCHIN_DIR
      
      - name: Build android sdk
        run: ./build_android.sh

      - name: list dir
        run: ls

      - name: list dir 2
        run: ls opencv
      
      - name: rename android
        run: |
          mkdir export
          mv android_sdk export/opencv

      - name: zip file
        run: 7z a -r opencv-${{ inputs.ref }}-android.zip ./export/opencv/

      
      - uses: actions/upload-artifact@v3
        name: upload artifacts
        with:
          name: artifact-android
          path: opencv-${{ inputs.ref }}-android.zip